name: Docker image CI

on:
  push:
    branches:
    - 'main'
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Docker Build
      run: docker build -t tvial/docker-tradingview-trader ./
      
    - name: Docker Push
      run: docker push tvial/docker-tradingview-trader